# Generated by Django 4.2.5 on 2023-10-06 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('video_name', models.CharField(max_length=150, null=True)),
                ('youtube_link_or_filename', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='processing', max_length=150)),
                ('VTT_file_Path', models.CharField(max_length=500, null=True)),
                ('SRT_file_Path', models.CharField(max_length=500, null=True)),
                ('TXT_file_Path', models.CharField(max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
            },
        ),
    ]
