# Generated by Django 4.2.5 on 2023-10-06 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('payment_intent_id', models.CharField(max_length=500)),
                ('selected_plan', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=200)),
                ('address_line1', models.CharField(max_length=500)),
                ('address_line2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('postal_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plan_expire_on', models.DateTimeField()),
                ('transaction_count', models.IntegerField()),
                ('remaining_transaction', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
